pads/urls.py
from django.conf.urls import url

from .views import PadCreateView, PadDetailSlugView, PadListView, PadUpdateView, PadDeleteView

urlpatterns = [
    url(r'^create/$', PadCreateView, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', PadDetailSlugView.as_view(), name='read'),
    url(r'^$', PadListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/update/$', PadUpdateView, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', PadDeleteView, name='delete'),
]

pond/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import UserCreationForm

from django.views.generic import TemplateView, CreateView
from django.views.decorators.csrf import csrf_exempt

from graphene_django.views import GraphQLView

from .views import RedirectView

urlpatterns = [
    url(r'^$', RedirectView, name='login'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^admin/', admin.site.urls),
    url('^register/', CreateView.as_view(
            template_name='registration/register.html',
            form_class=UserCreationForm,
            success_url='/'
    ), name='register'),
    url(r'^graphql', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    url(r'^hoppers/', include(('hoppers.urls', 'hoppers'), namespace='hopppers')),
    url(r'^pads/', include(('pads.urls', 'pads'), namespace='pads')),
    url(r'^events/', include(('events.urls', 'events'), namespace='events')),
    url(r'^ribbits/', include(('ribbits.urls', 'ribbits'), namespace='ribbits')),
]

pads/models.py
from __future__ import unicode_literals

import random
import os

from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.urls import reverse

from pond.utils import unique_slug_generator
from django.utils import timezone

from events.models import Event
from hoppers.models import Hopper

from cloudinary.models import CloudinaryField

class Pad(models.Model):
    name            = models.CharField(max_length=20)
    address         = models.CharField(max_length=100)
    description     = models.TextField(max_length=200)
    owner           = models.OneToOneField(Hopper, null=True, on_delete=models.SET_NULL)
    active          = models.BooleanField(default=True)
    slug            = models.SlugField(null=True, unique=True, editable=False)
    created_at      = models.DateTimeField(default=timezone.now)
    deleted_at      = models.DateTimeField(null=True, blank=True)
    image           = CloudinaryField('image', null=True, blank=True)
    caption         = models.CharField(max_length=100, null=True, blank=True)

    def __repr__(self):
        return str(self.name)

    def __str__(self):
        return str(self.name)

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Pad._meta.fields]

    def get_absolute_url(self):
        return reverse('pads:read', kwargs={'slug': self.slug})

    def get_events_list(self):
        return Event.objects.filter(pad=self).exclude(private=1)

def pad_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(pad_pre_save_receiver, sender=Pad)

pads/forms.py
from .models import Pad
from django.forms import ModelForm

class PadCreateForm(ModelForm):
    class Meta:
        model = Pad
        fields = ['name', 'address', 'description', 'image', 'caption']

class PadUpdateForm(ModelForm):
    class Meta:
        model = Pad
        fields = ['name', 'address', 'description', 'image', 'caption']

pads/views.py
from django.views.generic import UpdateView, ListView, DetailView
from django.http import Http404
from django.db import IntegrityError

from django.shortcuts import render, redirect

from .models import Pad
from hoppers.models import Hopper

from .forms import PadCreateForm, PadUpdateForm

import cloudinary.uploader

def PadCreateView(request):
    if request.method == "POST":
        try:
            form = PadCreateForm(request.POST, request.FILES)
            if form.is_valid():
                pad = form.save(commit=False)
                pad.image = cloudinary.uploader.upload(request.FILES)
                # The pad is always created by the current user.
                pad.owner = Hopper.objects.get(user=request.user)
                pad.save()
                return redirect('pads:read', pad.slug)
        except IntegrityError:
            return Http404('One pad per user.')
        except:
            raise Http404('Error in create view.')
    else:
        form = PadCreateForm()
        return render(request, 'pads/create_pad.html', {'form': form})

class PadDetailSlugView(DetailView):
    template_name = 'pads/detail.html'

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        try:
            instance = Pad.objects.get(slug=slug, active=True)
        except Pad.DoesNotExist:
            raise Http404('Pad does not exist')
        except Pad.MultipleObjectsReturned:
            qs = Pad.objects.filter(slug=slug, active=True)
            instance = qs.first()
        except:
            raise Http404('Error in slug view')
        return instance

class PadListView(ListView):
    queryset = Pad.objects.all()
    template_name = 'pads/list.html'

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Pad.objects.exclude(active=False)

def PadUpdateView(request, slug):
    try:
        pad = request.user.hopper.pad
    except:
        return Http404('You do not have a pad to update.')

    try:
        if request.method == "POST":
            form = PadUpdateForm(request.POST, request.FILES, instance=pad)
            if form.is_valid():
                pad = form.save(commit=False)
                pad.image = cloudinary.uploader.upload(request.FILES)
                pad.save()
                return redirect('pads:read', pad.slug)
        else:
            form = PadUpdateForm()
            return render(request, 'pads/update_pad.html', {'form': form})
    except:
        raise Http404('Error in update view.')

def PadDeleteView(request, slug):
    try:
        pad = request.user.hopper.pad
    except:
        return Http404('You do not have a pad to delete.')

    try:
        pad.active = False
        pad.save()
        return redirect('pads:list')
    except:
        raise Http404('Error in delete view.')

pads/templates/pads/create_pad.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" class="pad-form text-center">{% csrf_token %}
      <label for="name">Name:</label>
      <div class="form-group">
        {{ form.name }}
      </div>
      <label for="address">Address:</label>
      <div class="form-group">
        {{ form.address }}
      </div>
      <label for="description">Description:</label>
      <div class="form-group">
        {{ form.description }}
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

pads/templates/pads/detail.html
{% extends "base.html" %}
{% url 'events:create' as event_create_url %}
{% block content %}
  {% if object.owner == request.user.hopper %}
    <div class="text-center">
      <a href="update" class="btn btn-primary"<span class="badge">Update Pad</span></a>
      <a href="delete" class="btn btn-primary"<span class="badge">Delete Pad</span></a>
      </br>
      </br>
    </div>
  {% endif %}
  <div class="card">
    </br>
    <div class="card text-center">
      <div class="card-body">
        <h2 class="card-title">{{ object.name }}</h2>
        <h3>{{ object.address }}</h3>
        {% load cloudinary %}
        {% if object.image %}
          {% cloudinary object.image.public_id className="pad-pic" height=300 width=150 %}
          </br>
        {% endif %}
        {% if object.caption %}
          <div>{{ object.caption }}</div>
          </br>
        {% endif %}
        <div>{{ object.description }}</div>
        </br>
        Events:
        </br>
        {% for event in object.get_events_list %}
          <a href="{{ event.get_absolute_url }}" class="btn btn-default"<span class="badge">{{ event }}</span></a>
        {% endfor %}
        </br>
        </br>
      </div>
    </div>
  </div>
{% endblock %}

pads/templates/pads/list.html
{% extends 'base.html' %}
{% block content %}
  {% if not request.user.hopper.pad %}
    <div class="text-center">
        <a href="create" class="btn btn-primary"<span class="badge">Create Pad</a>
        </br>
        </br>
    </div>
  {% else %}
    <div class="text-center">
        <a href="{{request.user.hopper.pad.slug}}" class="btn btn-primary"<span class="badge">View Your Pad</a>
        </br>
        </br>
    </div>
  {% endif %}
  {% for obj in object_list %}
    {% include 'pads/snippets/card.html' with object=obj %}
    </br>
  {% endfor %}
{% endblock content %}

pads/templates/pads/update_pad.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST" class="pad-form text-center">{% csrf_token %}
      <label for="name">Name:</label>
      <div class="form-group">
        {{ form.name }}
      </div>
      <label for="address">Address:</label>
      <div class="form-group">
        {{ form.address }}
      </div>
      <label for="image">Picture:</label>
      <div class="form-group">
        {{ form.image }}
      </div>
      <label for="caption">Caption:</label>
      <div class="form-group">
        {{ form.caption }}
      </div>
      <label for="description">Description:</label>
      <div class="form-group">
        {{ form.description }}
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}