pads/urls.py
from django.conf.urls import url

from .views import PadCreateView, PadDetailSlugView, PadListView, PadUpdateView, PadDeleteView

urlpatterns = [
    url(r'^create/$', PadCreateView, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', PadDetailSlugView.as_view(), name='read'),
    url(r'^$', PadListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/update/$', PadUpdateView, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', PadDeleteView, name='delete'),
]

pond/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import UserCreationForm

from django.views.generic import TemplateView, CreateView
from django.views.decorators.csrf import csrf_exempt

from graphene_django.views import GraphQLView

from .views import RedirectView

urlpatterns = [
    url(r'^$', RedirectView, name='login'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^admin/', admin.site.urls),
    url('^register/', CreateView.as_view(
            template_name='registration/register.html',
            form_class=UserCreationForm,
            success_url='/'
    ), name='register'),
    url(r'^graphql', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    url(r'^hoppers/', include(('hoppers.urls', 'hoppers'), namespace='hopppers')),
    url(r'^pads/', include(('pads.urls', 'pads'), namespace='pads')),
    url(r'^events/', include(('events.urls', 'events'), namespace='events')),
    url(r'^ribbits/', include(('ribbits.urls', 'ribbits'), namespace='ribbits')),
]

templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' type="text/css">

<link rel='stylesheet' href='{% static "css/main.css" %}' type="text/css">

<link rel='stylesheet' href='{% static "css/navbar.css" %}' type="text/css">

templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS
slim is missing ajax -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

<!-- jquery-confirm JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

<!-- Django Secure AJAX JS -->
<script src='{% static "js/csrf.js" %}'></script>

<!-- Custom JS -->
<script src='{% static "js/pond.js" %}'></script>

templates/base/navbar.html
{% url 'hoppers:list' as hopper_list_url %}
{% url 'hoppers:update' as hopper_update_url %}
{% url 'pads:list' as pad_list_url %}
{% url 'events:list' as event_list_url %}
{% url 'ribbits:list' as ribbit_list_url %}
{% url 'register' as register_url %}
{% url 'login' as login_url %}

{% load static %}

<div class="icon-bar navbar-fixed-top">
  {% if request.user.is_authenticated %}
    <a class="nav-link nav-icon fa fa-commenting {% if request.path == ribbit_list_url %}active{% endif %}" href="{{ ribbit_list_url }}"></a>
    <a class="nav-link nav-icon fa fa-users {% if request.path == hopper_list_url %}active{% endif %}" href="{{ hopper_list_url }}"></a>
    <a class="nav-link nav-icon fa fa-calendar {% if request.path == event_list_url %}active{% endif %}" href="{{ event_list_url }}"></a>
    <a class="nav-link nav-icon fa fa-map-signs {% if request.path == pad_list_url %}active{% endif %}" href="{{ pad_list_url }}"></a>
    <a class="nav-link nav-icon fa fa-cogs {% if request.path == hopper_update_url %}active{% endif %}" href="{{ hopper_update_url }}"></a>
  {% else %}
    <a class="nav-link nav-icon {% if request.path == login_url or request.path == '/' %}active{% endif %}" href="{{ login_url }}">Login</a>
    <a class="nav-link nav-icon {% if request.path == register_url %}active{% endif %}" href="{{ register_url }}">Register</a>
  {% endif %}
</div>

templates/base/navbar_original.html
{% url 'home' as home_url %}
{% url 'hoppers:list' as hopper_list_url %}
{% url 'pads:list' as pad_list_url %}
{% url 'events:list' as event_list_url %}
{% url 'ribbits:list' as ribbit_list_url %}
{% url 'register' as register_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'contact' as contact_url %}

{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
    <div class="navbar-collapse collapse w-100">
        <ul class="navbar-nav ml-auto text-center">
          {% if request.user.is_authenticated %}
            <li class="nav-item {% if request.path == ribbit_list_url %}active{% endif %}">
              <a class="nav-link nav-icon fa fa-commenting" href="{{ ribbit_list_url }}"><span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.path == hopper_list_url %}active{% endif %}">
              <a class="nav-link nav-icon fa fa-users" href="{{ hopper_list_url }}"><span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.path == event_list_url %}active{% endif %}">
              <a class="nav-link nav-icon fa fa-calendar" href="{{ event_list_url }}"><span class="sr-only">(current)</span></a>
            </li>
          {% else %}
            <li class="nav-item {% if request.path == login_url %}active{% endif %}">
              <a class="nav-link nav-icon" href="{{ login_url }}">Login</a>
            </li>
          {% endif %}
        </ul>
    </div>
    <div class="navbar-collapse collapse w-100 dual-collapse2 order-2 order-md-2">
        <ul class="navbar-nav mr-auto text-center">
          {% if request.user.is_authenticated %}
            <li class="nav-item {% if request.path == pad_list_url %}active{% endif %}">
              <a class="nav-link nav-icon fa fa-map-signs" href="{{ pad_list_url }}"><span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <li class="nav-item dropdown">
                <a class="nav-link nav-icon fa fa-caret-square-o-down" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    {% if request.user.is_authenticated %}
                      <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
                    {% endif %}
                  </div>
              </li>
            </li>
          {% else %}
            <li class="nav-item {% if request.path == register_url %}active{% endif %}">
              <a class="nav-link nav-icon" href="{{ register_url }}">Register</a>
            </li>
          {% endif %}
        </ul>
    </div>
</nav>